# This is a basic workflow to help you get started with Actions

name: codeCoverage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: "*"
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies pytest
        run: python -m pip install build pytest pytest-cov numpy
      # - name: Build and install the autodiff_package in the container
      #   run: (python -m build --)
      # - name: Install dependencies numpy
      #   run: python3 -m pip install numpy
      - name: Run tests and generate coverage html
        run: (cd tests && bash run_tests.sh coverage)

      - name: Claim .gitignore in coverage output
        run: rm -f tests/htmlcov/.gitignore

      - name: Deploy test coverage github page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: tests/htmlcov

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: tests/cov.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '90'
