# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "*"
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  test_autodiff:
    name: Test Python implementation of the autodifferentiate package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: (python -m pip install build pytest && python -m pip install build numpy)
      - name: Run autodiff test suite
        run: (cd tests && bash run_tests.sh)

# jobs:
#     your_npm_job_name:
#         steps:
#           - uses: actions/checkout@v3
#           - uses: actions/setup-python@v3
#             with:
#               python-version: '3.10'
#           - name: Install Python dependencies
#             run: (python -m pip install build pytest && python -m pip install build numpy)
#           - name: Run autodiff test suite
#             run: (cd tests && bash run_tests.sh)

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: [ self-hosted ]

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
